export ClientPage from './client'
export ModeratorPage from './moderator'
export ModeratorLoginForm from './moderator-login-form'
export AddContactForm from './add-contact-form'
export AddNews from './add-news-form'
export ResidentsList from './residents-list'