export const GET_RESIDENTS_LIST = 'GET_RESIDENTS_LIST'
export const GET_RESIDENTS_LIST_SUCCESS = 'GET_RESIDENTS_LIST_SUCCESS'
export const GET_RESIDENTS_LIST_FAIL = 'GET_RESIDENTS_LIST_FAIL'

export const GET_BUILDINGS_LIST = 'GET_BUILDINGS_LIST'
export const GET_BUILDINGS_LIST_SUCCESS = 'GET_BUILDINGS_LIST_SUCCESS'
export const GET_BUILDINGS_LIST_FAIL = 'GET_BUILDINGS_LIST_FAIL'

export const GET_BUILDING = 'GET_BUILDING'
export const GET_BUILDING_SUCCESS = 'GET_BUILDING_SUCCESS'
export const GET_BUILDING_FAIL = 'GET_BUILDING_FAIL'

export const FETCH_SEND_RESIDENT = 'FETCH_SEND_RESIDENT'
export const FETCH_SEND_RESIDENT_SUCCESS = 'FETCH_SEND_RESIDENT_SUCCESS'
export const FETCH_SEND_RESIDENT_FAIL = 'FETCH_SEND_RESIDENT_FAIL'
